### ISSUE TITLE
Image size 384 

### ISSUE THREAD

**Issue by oggyfaker** [facebookresearch/deit#1]
Hi , how can i use model  DeIT base for image with size 384 ? I just typed the script with " deit_base_patch16_384" but it Cannot find callable deit_base_patch16_384 in hubconf

**Comment by TouvronHugo** [comment]
Hi @oggyfaker ,
Thank you for your question.
Currently we have not yet published the model weights for deit_base_patch16_384.
It should be added in the next update of the repo. We will also probably add the code for the fine-tuning as well as the distillation and the models that are related to it.

Best,

Hugo

**Comment by fmassa** [comment]
Hi,

We've added the code and models for the 384-resolution models in https://github.com/facebookresearch/deit/pull/43 and https://github.com/facebookresearch/deit/pull/50 , and the distilled models in https://github.com/facebookresearch/deit/pull/42

I'm closing this issue since we've added the aforementioned models, but let us know if you have any further questions
