### ISSUE TITLE
100 epoch or 300 epoch, which is correct?

### ISSUE THREAD

**Issue by bhheo** [facebookresearch/deit#13]
Hi

Thank you for you great work.
I'm trying to reproduce performance on ImageNet.
I have a question on training setting.

In the paper, you mentioned that
```Formally it means that we have 100 epochs, but each is 3x longer because of the repeated augmentations. We prefer to refer to this as 300 epochs```.
In the code, repeated augment is used by default
https://github.com/facebookresearch/deit/blob/4e91d2588f04954cd7a63f6a3eaeb01cd7127e0b/main.py#L106
But, training epochs is 300 epochs
https://github.com/facebookresearch/deit/blob/4e91d2588f04954cd7a63f6a3eaeb01cd7127e0b/main.py#L34

As I understand, it should be 100 epochs by the paper.
Is there any code that reduces actual training epochs ? or Should I train it for 300 epochs to reproduce the performance ?

**Comment by TouvronHugo** [comment]
Hi @bhheo ,
You have to use 300 epochs with repeated_aug = True. In the code we make sure that the size of an epoch doesn't vary, so we don't see all the dataset images during one epoch with repeated_aug=True. Indeed, we see exactly 1/3 of the dataset images during one epoch. That's why we wrote in the article: `Formally it means that we have 100 epochs, but each is 3x longer because of the repeated augmentations. We prefer to refer to this as 300 epochs`.
I hope I have answered your question.
Best,
Hugo

**Comment by bhheo** [comment]
I missed this part
https://github.com/facebookresearch/deit/blob/4e91d2588f04954cd7a63f6a3eaeb01cd7127e0b/samplers.py#L57
Thanks for your quick and kind answer.
