### ISSUE TITLE
The result on CIFAR10

### ISSUE THREAD

**Issue by DOHA-HWANG** [facebookresearch/deit#154]
Hello,
Thank you for sharing your valuable codes.
I modified your codes for CIFAR10 (without pre-trained), and my result was just around 81%. (ViT was 79%)
I used resnet50 (ACC was around 94%) as a teacher network.

Although it was better than the ViT, the result was very low compared to the teacher's performance.
It seems that I made something wrong with my codes.

Do you have some results on CIFAR10 (without any other dataset).

And if you have some advice, please reply to it.

**Comment by TouvronHugo** [comment]
Hi @DOHA-HWANG,
Thanks for your question, 
Yes, as mentioned p14 in the paper (arXiv version) we reach 98.5% on CIFAR10 only with ViT-B and a teacher network pre-trained on CIFAR-10 only.
Since we kept the patch size at 16 and kept the RegNet-16GF as a teacher we train on CIFAR-10 at 224x224 resolution by upscaling the images. We train for 1000 epochs.
Let me know if you need more details.
Best,
Hugo

**Comment by DOHA-HWANG** [comment]
Thank you for your reply:) I didn't resize it. I will fix it as well.
Have a nice day.
