### ISSUE TITLE
Data structure and GPU problem?

### ISSUE THREAD

**Issue by Wang-Y-S** [facebookresearch/deit#164]
hi author
I am a CV newbie,
Currently working on your thesis
I find that your outstanding contribution in the field of VIT makes me very admire,
I would like to try to study the content through the code you provided
But I found that I have encountered several problems,
First
The Val of your Imagenet says that there are folders divided into different categories, but when I downloaded imagenet2012, there was no folder structure like yours
second
if I just use a single GPU3060 RAM12G,Can i reproduce your result?

Hope you can give me your opinion thank you!!

**Comment by TouvronHugo** [comment]
Hi @Wang-Y-S,
Thanks for your message and very happy that you like our work.
Yes, in this case you have to reorganize the downloaded elements in order to have a structure with one folder for each class.
I think in this case it may be possible to reproduce the results with smaller models by adding gradient accumulation and checkpointing and maybe try smaller resolutions.
Best,
Hugo

**Comment by Wang-Y-S** [comment]
Thank you very much for your reply
I will try what you suggested
If I encounter any new problems
I will ask you again
Thank you very much
Wang-Y-S
