### ISSUE TITLE
Can you release the training logs of deit on imagenet?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/deit#18]
As the title implies, it would be great to share the training log of imagenet.

**Comment by TouvronHugo** [comment]
Hi @gaopengcuhk,
Thanks for your suggestion, we will share our training logs.
Best,
Hugo

**Comment by greeneggsandyaml** [comment]
Thank you! I was just coming here to ask whether you could share the logs as well :)

**Comment by ZhangChao1993** [comment]
Thank you! I was just coming here to ask whether you could share the logs as well :)

**Comment by fmassa** [comment]
Hi, following the comment on https://github.com/facebookresearch/deit/issues/16#issuecomment-756764324, here are the training logs for DeiT-small trained on ImageNet, using both 4 and 16 GPUs
https://gist.github.com/fmassa/0dbd0184a0adb904ef42277b487d8b53

They do not correspond exactly to the models released, but are within random variation.

I'll be sending the training logs for the other models at a later stage

**Comment by chunfuchen** [comment]
@fmassa do you mind sharing the log for the base model? When I try to reproduce, the model seems to diverge after the 5-th epoch, but it back to normal after a few epochs. And I can get the same accuracy as you did (81.8%)

Furthermore, when I change the warmup to 10 epochs instead of 5 epochs. The above issue is disappeared; however, there is significant performance degradation. This model only achieves 79.2%. 
Do you have insight that simply warmup 5 epochs more can result in such a difference?

Thanks.

**Comment by TouvronHugo** [comment]
As there is no more activity on this issue, I am closing it. Don't hesitate to reopen it if necessary.
