### ISSUE TITLE
Question about experiment results in paper

### ISSUE THREAD

**Issue by CoinCheung** [facebookresearch/deit#19]
Hi,

Thanks for release the code of this great work. I found that in table 6 of the paper that `DeiT-B` trained on 224x224 images achieved top1 acc of 81.8, which `ViT-B/16` achieved top1 acc 77.9(trained on 384x384 images). Do `DeiT-B` and `ViT-B/16` have same model structure? If yes, why is `ViT-B/16` achieves smaller acc even trained on large images?

**Comment by TouvronHugo** [comment]
Hi @CoinCheung ,
Thank you for your question. Without fine-tuning DeiT-B and ViT-B/16 have almost the same structure. The unique model structure difference is that for pre-training DeiT-B does not use an MLP just a linear classifier. 
The difference in performance in this particular case is mainly  due to the optimization procedure.
I hope I have answered your question.
Best,
Hugo
