### ISSUE TITLE
Image throughput numbers

### ISSUE THREAD

**Issue by rwightman** [facebookresearch/deit#38]
What do the image / sec throughput numbers represent (train, inferences, batch size, mixed-prc or float32, etc)? They are lower than any inference numbers I'm familiar with for any of the listed models. They also don't seem to match expected training throughputs and have an odd spread (smallest to largest models), being quite low for the smaller models (CPU bound?).

I don't spend much time with V100, but relative to Titan RTX and RTX 3090 I have a fairly good idea where the numbers should fall...

Thanks

**Comment by TouvronHugo** [comment]
Hi @rwightman,
Thanks for your question,
Image / sec throughput numbers represent inferences time with 1 GPU V100 16GB with the maximum batch size for each model (with float32).   I think that measured values may vary depending on the type of GPU used, the version of cuda, etc...
Nevertheless, the results should remain proportional. I think that the closest measure of image / sec throughput  to ours may be the one on the [sotabench website](https://sotabench.com/benchmarks/image-classification-on-imagenet).
I hope I have answered your question. 
Best,
Hugo

**Comment by rwightman** [comment]
Thanks for the response, these models run quite well in mixed-prec (you train with it), and it looks like they are dataloader/CPU bound at the smaller end, Pillow-SIMD w/ libjpeg-turbo helps the sotabench numbers significantly. Your tiny should be above 2000img/s

**Comment by TouvronHugo** [comment]
Hi @rwightman ,
In our evaluation we included a generation of a random input during inference, which may explain the discrepancy with your numbers since this time can be saved in practice if we generate the matrix. This is a cost that depends on batch size (and therefore larger for smaller models), which is fully aligned with your observation. 
We have regenerated the numbers with an improved script that takes this computation out of the loop. Currently the numbers that we have are as follows:

tf_efficientnet_b7: 55.16 im/s
tf_efficientnet_b6: 96.98 im/s
tf_efficientnet_b5: 169.11 im/s
tf_efficientnet_b4: 349.40 im/s
tf_efficientnet_b3: 732.14 im/s
tf_efficientnet_b2: 1255.73 im/s
tf_efficientnet_b1: 1662.50 im/s
tf_efficientnet_b0: 2694.36 im/s

deit_tiny_patch16_224: 2536.53 im/s
deit_small_patch16_224: 940.41 im/s
deit_base_patch16_224: 291.05 im/s

vit_base_patch16_384: 85.87 im/s
vit_large_patch16_384: 27.29 im/s

Indeed with that updated evaluation script, the absolute numbers are much faster and especially for the smaller models, for which this operation was becoming dominent when adjusting the batch size so as to fit a maximum number of images. 
Attached the updated curve with the new results we have so far (still waiting for an updated improved Deit-S).

Thanks a lot for the feedback. That's ultra valuable!

Best,

Hugo

![curve](https://user-images.githubusercontent.com/49280617/104354586-b2565100-5509-11eb-9d53-78266c1e1ff6.png)

**Comment by TouvronHugo** [comment]
We will share the updated evaluation script shortly ;)

**Comment by jegou** [comment]
For the curious ones, the new Deit-B-distil-384 achieves 85.2% top-1 acc.

**Comment by fmassa** [comment]
Hi @rwightman 

Thanks for the very valuable feedback!

Here is the updated script for the throughput calculation -- it is expected to be found in the root of deit repo, as it imports our new model definitions https://gist.github.com/fmassa/1f4edb34ca041634c9b730473753b8ad

Let us know if you have any further comments / feedback.

**Comment by fmassa** [comment]
We've updated the figure in the repo and the paper with the new throughput calculation in https://github.com/facebookresearch/deit/pull/53 so I'm closing this issue, once again thanks for spotting this @rwightman !
