### ISSUE TITLE
Question about KLDiv computation

### ISSUE THREAD

**Issue by chunfuchen** [facebookresearch/deit#61]
At line https://github.com/facebookresearch/deit/blob/main/losses.py#L54

The sum of KLDiv is divided by `outputs_kd.numel()`, should it be divided by `output_kd.size(0)`? That is average over batch only.
The current code works as setting `reduction='mean'`.

In pytorch 1.7 documentation, https://pytorch.org/docs/stable/generated/torch.nn.KLDivLoss.html,
the last note pointed out `batchmean` equal to the real math definition of KLDiv.

**Comment by TouvronHugo** [comment]
Hi @chunfuchen ,
Excellent remark,
You are right, we had originally implemented KLDiv with the legacy PyTorch behavior, but that upon code release we changed it so that results could be reproduced even after PyTorch updates the behavior of KLDiv. 
We did some tests with reduction=batchmean and obtained slightly lower/similar performance.
I hope I have answered your question. 
Best,
Hugo

**Comment by chunfuchen** [comment]
@TouvronHugo Thanks for the clarification.
