### ISSUE TITLE
Dataset Size

### ISSUE THREAD

**Issue by ghost-ronin** [facebookresearch/deit#8]
I'm trying out the code with a custom dataset that has about 8k training images and 550 validation images. Is it enough for this method ?

**Comment by TouvronHugo** [comment]
Hi @ghost-ronin,
Very good question, it is not easy to answer because I think that the answer also depends on other parameters such as the number of classes, how they are balanced,...
I would tend to say that the method should work but I think it's best to try. 
For example, you can test first with our DeiT-tiny (5M parameters half the size of ResNet-18), it is quite fast to train.
Best,
Hugo

**Comment by ghost-ronin** [comment]
> Hi @ghost-ronin,
> Very good question, it is not easy to answer because I think that the answer also depends on other parameters such as the number of classes, how they are balanced,...
> I would tend to say that the method should work but I think it's best to try.
> For example, you can test first with our DeiT-tiny (5M parameters half the size of ResNet-18), it is quite fast to train.
> Best,
> Hugo
Hi @TouvronHugo 
    I will try this model and then write to you.
